---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: taskapp-secrets
  namespace: taskapp
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBrY42+cOvu6j93IIz083fABWjWJeCg3ThQD0MKynYKc3C1WD6xSBPHpu5iQPK3++AB7TuykJyC9CITPgX2MpW9WlCmdhwHkStvGSUMjUfCEvIc06847iYyMDy+lpA9P3L2rXmPAaOnfCZym2AhFW3wLm1ze7XOpwzXdj39aLOuQIvXYgyLIUV0TIjbBDc9lDGJny3dNyEVsBTq9+OVx2NTME1vO8mUvlc+IwNvD5YZWsXalp+EG1UGyD8EH11aAWMQ/z7ak38icQknlx1nqE5rhpf+sB3OVwubzBELJ09QxPR7+FpURTsyRSThhTyP9SuaTU5M9lmzuvtCfh1tV6KnlhqAvh8PNixxSLvwGGpy4CCnPChGbJ/kDvL8p2FTy5ftlftwyCQAqejrOFWAdFTzVRyhBY8aVSliwBLi3tzeO4uF8GWfzGIvCrGS9OA9mDhEFdUUsZ+MVGbNFcqxNANjJgg37wmDMQfkSYbPyK/EUp9vNrh/Qx1AjpfVp0BZN1XKXps6BwKDioL+17qktX+0m4kSvSPvg5x0mRPLjDcMLj/bsw6TvrGw3Xu9wFM6WBLq3ptnLAmlVzyV3gBOPX5ERjP+nN9LAj3XPueadOjC3Gjw+cTq9DhnU9QZfGnSteGewAjruqqmqeh/ViUYx3N4SpLylIkJ5LJ2tbK0LAnKnlJeBdp3McMeE7A+kTC3kNpSoj/tcXLgxzdzfaZPJ1HOikaM4JRk8e6fl4sPlFWafTtnD1mxpaUcdVDz/A==
    SECRET_KEY: AgCm6NsMv5p5KkqfyDvy8310AnR5iFRYJ0TxPh7K1oVysT6Z8RiKrcq1iICiFji6eMR7PjiggRdB1ZYTrlRVfGXb+KuhDaf7E/haZZCWD+pKdMg0WIHStIAVFN66TuzRBiiqO/XeArr6GtJWrXz6Zk6YwSbXkCA2s/I0cfuElFWJ+qsVfjElcvR2T2oiODHUHopXCh+IZJLzj2UlyWv4qlw9JS3s0a2DbxolqpupsgrXJpbucUAXrcMPPtB2HHTK2mJ+YABRorbfxkbdcfcHpyfKmrXLgjX0T748H1BlRLArHU/xDPOSZU1p8aJla2p1GzJZZB99YbaEBLBzSY1t23sLUgHhikd1XVuXmvLiTO7Zj1DIu+PSxiMN0xZHr+CfsvPNXTtbuUCNRFTgCAqkHSkiYCdc1tCanL1kl3W8vfSGfzgGurnAeITc7PvqS5M+oU67WuWQMeOjWdk86qMpohG3NNI3kOjf5aXJSHJaAX9JAFIQYMLnQA4/ONbwLUOzfFrVgi7BSK5Kc9oET8/CUPYUK1ky7NIpKvm2SulTsX37c8VJ33DwRXuNTiHz5O6VKngFlTIA4SWwizLzbEEiKIJCnhDovc78QzN0dU3SgiSAowrNreTcLaLVEgzh9Vmw055kiBaSll91jury07d6DEjam2rTYaLI+TxnpHkcRP+uuRCE2Kv0a7UFFjaOYAF4onTs+VhKdYUiNk/uLevfAM1aAf4BPSb50A0BQ4Ph5KfLJXEIuWK8Q+6d+eIbcQ==
  template:
    metadata:
      creationTimestamp: null
      name: taskapp-secrets
      namespace: taskapp
