# helm/taskapp/values-dev.yaml
# Development values
namespace: taskapp-dev

images:
  backend:
    tag: "5d6b8fc"
  frontend:
    tag: "26da2b0"

replicaCount:
  backend: 1
  frontend: 1

postgresql:
  persistence:
    size: 5Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

backend:
  env:
    FLASK_ENV: development
    CORS_ORIGINS: "http://localhost:8080,http://localhost:3000"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

secrets:
  enabled: true # Enables secrets.yaml for local Helm deploys
  postgresPassword: "dev_password_change_me"
  secretKey: "dev_secret_key_change_me"

sealedSecrets:
  enabled: false #  Disables sealedsecret.yaml to prevent conflicts

httpRoute:
  enabled: false

externalAccess:
  host: taskapp.dev.local
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: taskapp.local
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 5000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
  tls:
    enabled: true
    issuer: selfsigned-cluster-issuer
