# helm/argocd/values-prod.yaml
ingress:
  enabled: true
  host: argocd.prod.local
  className: nginx
  tls: true
  extraAnnotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
